<#	
	.NOTES
	===========================================================================
	 Created on:   	17/09/2024 10:01
	 Created by:   	Phil Factor
	===========================================================================
	.DESCRIPTION
		if the flyway user placeholder 'CurrentSettings' has a value, this routine
	which needs to be run in a script or callback, finds all the flyway settings made
	for the connection and saves them in the user area as a JSON file.
        it will, if you provide the filename, create a powershell file that will,
        if then executed,set all the environment variables in place
    .NOTE
    For this to work, you would need to set up special environment variables to tell
    the routine where to save the information
    e.g.
    $Env:FP__FlywayEnVs__='Create-OurFlywayENVs'
    
#>
# this delete routine doesn't happen in this script, it is part of the generated
# script
$DeleteAllFlywayENVs = @'
# This script deletes the current Flyway Envs and replaces them with this set
# recorded and generated by a script executed by beforeInfo_Env.ps1
(gci env:FP__*) + (gci env:Flyway_*) | foreach { remove-item "env:$($_.Name)" }
'@
if ($Env:FP__FlywayEnVs__ -ne $null)
# if the Env has a value
{
	# get all the Flyway variable and placeholder values held in the session environment
	('env:FLYWAY_*', 'env:FP__*') | foreach{ gci $_ } | sort-object name | foreach-object -Begin {
		$TheList = @{ };
	} -Process {
		$TheList[$_.Name] = $_.Value;
	} -end {
		($TheList.Keys | foreach -begin { $DeleteAllFlywayENVs }{ "`$Env:$($_)='$($TheList[$_])';" }
		)>"$env:USERPROFILE\$($Env:FP__FlywayEnVs__).ps1"
	}
}

