echo %FLYWAY_EDITION%
echo %FLYWAY_PASSWORD%
echo %FLYWAY_URL%
echo %FLYWAY_USER%
echo %FP__Branch__%
echo %FP__flyway_database__%
echo %FP__flyway_defaultSchema__%
echo %FP__flyway_filename__%
echo %FP__flyway_table__%
echo %FP__flyway_timestamp__%
echo %FP__flyway_user__%
echo %FP__flyway_workingDirectory__%
