ALTER TABLE dbo.employee DROP CONSTRAINT FK_EMPLOYEEPUBLISHERS;
ALTER TABLE dbo.Pub_Info DROP CONSTRAINT FK_PUB_INFOPUBLISHERS;
ALTER TABLE dbo.titles DROP CONSTRAINT FK_TITLESPUBLISHERS;

-- 'Altering dbo.employee'
ALTER TABLE dbo.employee modify pub_id char (8);

-- ''Altering dbo.publishers'

ALTER TABLE dbo.publishers modify pub_id char (8);

-- ''Altering dbo.pub_info'

ALTER TABLE dbo.pub_info modify pub_id char (8);

-- ''Altering dbo.titles'

drop view dbo.titleview;

ALTER TABLE dbo.titles modify pub_id char (8);

ALTER TABLE dbo.employee 
    ADD CONSTRAINT FK_EMPLOYEEPUBLISHERS FOREIGN KEY (pub_id) REFERENCES dbo.publishers (pub_id);
ALTER TABLE dbo.Pub_Info 
    ADD CONSTRAINT FK_PUB_INFOPUBLISHERS FOREIGN KEY (pub_id) REFERENCES dbo.publishers (pub_id);
ALTER TABLE dbo.titles  
    ADD CONSTRAINT FK_TITLESPUBLISHERS FOREIGN KEY (pub_id) REFERENCES dbo.publishers (pub_id);


CREATE OR REPLACE VIEW dbo.titleview
AS 
Select title, au_ord, au_lname, price, ytd_sales, pub_id
from dbo.titleauthor  inner join dbo.titles
on titles.title_id = titleauthor.title_id
inner join dbo.authors
on dbo.authors.au_id = dbo.titleauthor.au_id;

-- ''Creating dbo.publications'
CREATE TABLE dbo.publications
(
Publication_id VARCHAR2(6) NOT NULL primary key,
title character varying (255) NOT NULL,
pub_id char(8) NULL,
notes NVARCHAR2(4000) NULL,
pubdate date  DEFAULT (sysdate)
);


-- ''Creating dbo.editions'
CREATE TABLE dbo.editions
(
Edition_id NUMBER(5,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE Primary Key,
publication_id VARCHAR2(6) NOT NULL,
Publication_type character varying (20) DEFAULT ('book'),
EditionDate date DEFAULT (SYSDATE)
);

-- ''Creating dbo.prices'
CREATE TABLE dbo.prices
(
Price_id NUMBER(5,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE  Primary Key,
Edition_id int NULL,
price NUMBER(9,2) NULL,
advance NUMBER(9,2) NULL,
royalty NUMBER(10),
ytd_sales NUMBER(10),
PriceStartDate date DEFAULT (Sysdate),
PriceEndDate date NULL
);

