-- drop table dbo.titles
-- PROMPT Creating TABLE dbo.titles ...
CREATE TABLE dbo.titles (
  title_id NVARCHAR2(6) NOT NULL,
  title VARCHAR2(80 CHAR) NOT NULL,
  type CHAR(12 CHAR) NOT NULL,
  pub_id CHAR(4 CHAR),
  price NUMBER(19,4),
  advance NUMBER(19,4),
  royalty NUMBER(10,0),
  ytd_sales NUMBER(10,0),
  notes VARCHAR2(200 CHAR),
  pubdate DATE NOT NULL
);


ALTER TABLE dbo.titles MODIFY (type DEFAULT 'UNDECIDED');
ALTER TABLE dbo.titles MODIFY (pubdate DEFAULT SYSDATE);
-- PROMPT Creating Primary Key Constraint UPKCL_titleidind on TABLE dbo.titles ... 
ALTER TABLE dbo.titles
ADD CONSTRAINT UPKCL_titleidind PRIMARY KEY
(
  title_id
)
ENABLE
;

-- PROMPT Creating TABLE dbo.authors ...
CREATE TABLE dbo.authors (
  au_id NVARCHAR2(11) NOT NULL,
  au_lname VARCHAR2(40 CHAR) NOT NULL,
  au_fname VARCHAR2(20 CHAR) NOT NULL,
  phone CHAR(12 CHAR) NOT NULL,
  address VARCHAR2(40 CHAR),
  city VARCHAR2(20 CHAR),
  state CHAR(2 CHAR),
  zip CHAR(5 CHAR),
  contract NUMBER(1,0) NOT NULL
);


ALTER TABLE dbo.authors MODIFY (phone DEFAULT 'UNKNOWN');
-- PROMPT Creating Primary Key Constraint UPKCL_auidind on TABLE dbo.authors ... 
ALTER TABLE dbo.authors
ADD CONSTRAINT UPKCL_auidind PRIMARY KEY
(
  au_id
)
ENABLE
;
-- PROMPT Creating Check Constraint CK__authors__au_id__239E4DCF on TABLE dbo.authors... 
ALTER TABLE dbo.authors
ADD CONSTRAINT CK__authors__au_id__239E4DCF CHECK 
(
   ( REGEXP_LIKE(au_id, '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]') )
) 
ENABLE
;
-- PROMPT Creating Check Constraint CK__authors__zip__25869641 on TABLE dbo.authors... 
ALTER TABLE dbo.authors
ADD CONSTRAINT CK__authors__zip__25869641 CHECK 
(
   ( REGEXP_LIKE(zip, '[0-9][0-9][0-9][0-9][0-9]') )
) 
ENABLE
;

-- PROMPT Creating TABLE dbo.publishers ...
CREATE TABLE dbo.publishers (
  pub_id CHAR(4 CHAR) NOT NULL,
  pub_name VARCHAR2(40 CHAR),
  city VARCHAR2(20 CHAR),
  state CHAR(2 CHAR),
  country VARCHAR2(30 CHAR)
);


ALTER TABLE dbo.publishers MODIFY (country DEFAULT 'USA');
-- PROMPT Creating Primary Key Constraint UPKCL_pubind on TABLE dbo.publishers ... 
ALTER TABLE dbo.publishers
ADD CONSTRAINT UPKCL_pubind PRIMARY KEY
(
  pub_id
)
ENABLE
;
-- PROMPT Creating Check Constraint CK__publisher__pub_i__286302EC on TABLE dbo.publishers... 
ALTER TABLE dbo.publishers
ADD CONSTRAINT CK__publisher__pub_i__286302EC CHECK 
(
   ( pub_id = '1756'
                  OR pub_id = '1622'
                  OR pub_id = '0877'
                  OR pub_id = '0736'
                  OR pub_id = '1389'
                  OR REGEXP_LIKE(pub_id, '99[0-9][0-9]') )
) 
ENABLE
;

-- PROMPT Creating TABLE dbo.pub_info ...
CREATE TABLE dbo.pub_info (
  pub_id CHAR(4 CHAR) NOT NULL,
  logo BLOB,
  pr_info NCLOB
);


-- PROMPT Creating Primary Key Constraint UPKCL_pubinfo on TABLE dbo.pub_info ... 
ALTER TABLE dbo.pub_info
ADD CONSTRAINT UPKCL_pubinfo PRIMARY KEY
(
  pub_id
)
ENABLE
;

-- PROMPT Creating TABLE dbo.titleauthor ...
CREATE TABLE dbo.titleauthor (
  au_id NVARCHAR2(11) NOT NULL,
  title_id NVARCHAR2(6) NOT NULL,
  au_ord NUMBER(3,0),
  royaltyper NUMBER(10,0)
);


-- PROMPT Creating Primary Key Constraint UPKCL_taind on TABLE dbo.titleauthor ... 
ALTER TABLE dbo.titleauthor
ADD CONSTRAINT UPKCL_taind PRIMARY KEY
(
  au_id,
  title_id
)
ENABLE
;


-- PROMPT Creating TABLE dbo.discounts ...
CREATE TABLE dbo.discounts (
  discounttype VARCHAR2(40 CHAR) NOT NULL,
  stor_id CHAR(4 CHAR),
  lowqty NUMBER(5,0),
  highqty NUMBER(5,0),
  discount NUMBER(4,2) NOT NULL
);



-- PROMPT Creating TABLE dbo.jobs ...
CREATE TABLE dbo.jobs (
  job_id NUMBER(5,0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE ,
  job_desc VARCHAR2(50 CHAR) NOT NULL,
  min_lvl NUMBER(3,0) NOT NULL,
  max_lvl NUMBER(3,0) NOT NULL
);


ALTER TABLE dbo.jobs MODIFY (job_desc DEFAULT 'New Position - title not formalized yet');
-- PROMPT Creating Primary Key Constraint PK__jobs__6E32B6A586298717 on TABLE dbo.jobs ... 
ALTER TABLE dbo.jobs
ADD CONSTRAINT PK__jobs__6E32B6A586298717 PRIMARY KEY
(
  job_id
)
ENABLE
;
-- PROMPT Creating Check Constraint CK__jobs__min_lvl__3F466844 on TABLE dbo.jobs... 
ALTER TABLE dbo.jobs
ADD CONSTRAINT CK__jobs__min_lvl__3F466844 CHECK 
(
   ( min_lvl >= (10) )
) 
ENABLE
;
-- PROMPT Creating Check Constraint CK__jobs__max_lvl__403A8C7D on TABLE dbo.jobs... 
ALTER TABLE dbo.jobs
ADD CONSTRAINT CK__jobs__max_lvl__403A8C7D CHECK 
(
   ( max_lvl <= (250) )
) 
ENABLE
;

-- PROMPT Creating TABLE dbo.sales ...
CREATE TABLE dbo.sales (
  stor_id CHAR(4 CHAR) NOT NULL,
  ord_num VARCHAR2(20 CHAR) NOT NULL,
  ord_date DATE NOT NULL,
  qty NUMBER(5,0) NOT NULL,
  payterms VARCHAR2(12 CHAR) NOT NULL,
  title_id NVARCHAR2(6) NOT NULL
);


-- PROMPT Creating Primary Key Constraint UPKCL_sales on TABLE dbo.sales ... 
ALTER TABLE dbo.sales
ADD CONSTRAINT UPKCL_sales PRIMARY KEY
(
  stor_id,
  ord_num,
  title_id
)
ENABLE
;


-- PROMPT Creating TABLE dbo.roysched ...
CREATE TABLE dbo.roysched (
  title_id NVARCHAR2(6) NOT NULL,
  lorange NUMBER(10,0),
  hirange NUMBER(10,0),
  royalty NUMBER(10,0)
);


-- PROMPT Creating TABLE dbo.employee ...
CREATE TABLE dbo.employee (
  emp_id CHAR(9 CHAR) NOT NULL,
  fname VARCHAR2(20 CHAR) NOT NULL,
  minit CHAR(1 CHAR),
  lname VARCHAR2(30 CHAR) NOT NULL,
  job_id NUMBER(5,0) NOT NULL,
  job_lvl NUMBER(3,0),
  pub_id CHAR(4 CHAR) NOT NULL,
  hire_date DATE NOT NULL
);


ALTER TABLE dbo.employee MODIFY (job_id DEFAULT (1));
ALTER TABLE dbo.employee MODIFY (job_lvl DEFAULT (10));
ALTER TABLE dbo.employee MODIFY (pub_id DEFAULT '9952');
ALTER TABLE dbo.employee MODIFY (hire_date DEFAULT SYSDATE);
-- PROMPT Creating Primary Key Constraint PK_emp_id on TABLE dbo.employee ... 
ALTER TABLE dbo.employee
ADD CONSTRAINT PK_emp_id PRIMARY KEY
(
  emp_id
)
ENABLE
;
-- PROMPT Creating Check Constraint CK_emp_id on TABLE dbo.employee... 
ALTER TABLE dbo.employee
ADD CONSTRAINT CK_emp_id CHECK 
(
   ( REGEXP_LIKE(emp_id, '[A-Z][A-Z][A-Z][1-9][0-9][0-9][0-9][0-9][FM]')
                  OR REGEXP_LIKE(emp_id, '[A-Z]-[A-Z][1-9][0-9][0-9][0-9][0-9][FM]') )
) 
ENABLE
;

-- PROMPT Creating TABLE dbo.stores ...
CREATE TABLE dbo.stores (
  stor_id CHAR(4 CHAR) NOT NULL,
  stor_name VARCHAR2(40 CHAR),
  stor_address VARCHAR2(40 CHAR),
  city VARCHAR2(20 CHAR),
  state CHAR(2 CHAR),
  zip CHAR(5 CHAR)
);


-- PROMPT Creating Primary Key Constraint UPK_storeid on TABLE dbo.stores ... 
ALTER TABLE dbo.stores
ADD CONSTRAINT UPK_storeid PRIMARY KEY
(
  stor_id
)
ENABLE
;

CREATE INDEX titleindex ON dbo.titles
(
  title
) 
;
-- PROMPT Creating Index aunmind on authors ...
CREATE INDEX aunmindex ON dbo.authors
(
  au_lname,
  au_fname
) 
;
-- PROMPT Creating Index auidind on titleauthor ...
CREATE INDEX auidindex ON dbo.titleauthor
(
  au_id
) 
;
-- PROMPT Creating Index titleidind on titleauthor ...
CREATE INDEX titleidindex ON dbo.titleauthor
(
  title_id
) 
;
-- PROMPT Creating Index titleidind_2 on sales ...
CREATE INDEX titleidindex_2 ON dbo.sales
(
  title_id
) 
;
-- PROMPT Creating Index titleidind_1 on roysched ...
CREATE INDEX titleidindex_1 ON roysched
(
  title_id
) 
;







-- PROMPT Creating Index employee_ind on employee ...
CREATE INDEX employee_index ON dbo.employee
(
  fname,
  minit,
  lname
) 
;

CREATE OR REPLACE FORCE VIEW dbo.titleview 
AS 
   SELECT title ,
          au_ord ,
          au_lname ,
          price ,
          ytd_sales ,
          pub_id 
     FROM dbo.authors ,
          dbo.titles ,
          dbo.titleauthor 
    WHERE  authors.au_id = titleauthor.au_id
             AND titles.title_id = titleauthor.title_id;

CREATE OR REPLACE PROCEDURE dbo.byroyalty
(
  v_percentage IN NUMBER
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT au_id 
        FROM titleauthor 
       WHERE  titleauthor.royaltyper = v_percentage ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
END;


CREATE OR REPLACE PROCEDURE dbo.reptq1
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT CASE 
                  WHEN GROUPING(pub_id)  = 1 THEN 'ALL'
             ELSE pub_id
                END pub_id  ,
             AVG(price)  avg_price  
        FROM titles 
       WHERE  price IS NOT NULL
        GROUP BY ROLLUP( pub_id )
        ORDER BY pub_id ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
END;

CREATE OR REPLACE PROCEDURE dbo.reptq2
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT CASE 
                  WHEN GROUPING(TYPE)  = 1 THEN 'ALL'
             ELSE TYPE
                END TYPE  ,
             CASE 
                  WHEN GROUPING(pub_id)  = 1 THEN 'ALL'
             ELSE pub_id
                END pub_id  ,
             AVG(ytd_sales)  avg_ytd_sales  
        FROM titles 
       WHERE  pub_id IS NOT NULL
        GROUP BY ROLLUP( pub_id,TYPE ) ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
END;
CREATE OR REPLACE PROCEDURE dbo.reptq3
(
  v_lolimit IN NUMBER,
  v_hilimit IN NUMBER,
  v_type IN CHAR
)
AS
   v_cursor SYS_REFCURSOR;

BEGIN

   OPEN  v_cursor FOR
      SELECT CASE 
                  WHEN GROUPING(pub_id)  = 1 THEN 'ALL'
             ELSE pub_id
                END pub_id  ,
             CASE 
                  WHEN GROUPING(TYPE)  = 1 THEN 'ALL'
             ELSE TYPE
                END TYPE  ,
             COUNT(title_id)  cnt  
        FROM titles 
       WHERE  price > v_lolimit
                AND price < v_hilimit
                AND TYPE = v_type
                OR TYPE LIKE '%cook%'
        GROUP BY ROLLUP( pub_id,TYPE ) ;
      DBMS_SQL.RETURN_RESULT(v_cursor);
END;
/
/*
CREATE OR REPLACE TRIGGER dbo.employee_insupd
   BEFORE INSERT OR UPDATE
   ON dbo.employee
   FOR EACH ROW
DECLARE
   --Get the range of level for this job type from the jobs table.
   v_min_lvl NUMBER(3,0);
   v_max_lvl NUMBER(3,0);
   v_emp_lvl NUMBER(3,0);
   v_job_id NUMBER(5,0);

BEGIN
   SELECT min_lvl ,
          max_lvl ,
          :NEW.job_lvl ,
          :NEW.job_id 

     INTO v_min_lvl,
          v_max_lvl,
          v_emp_lvl,
          v_job_id
     FROM employee e,
          jobs j
    WHERE  e.emp_id = :NEW.emp_id
             AND :NEW.job_id = j.job_id;
   IF ( v_job_id = 1 )
     AND ( v_emp_lvl <> 10 ) THEN
    
   BEGIN
      raise_application_error(-20001, 'Job id 1 expects the default level of 10.' );
      ROLLBACK;
   END;
   ELSE
      IF NOT ( v_emp_lvl BETWEEN v_min_lvl AND v_max_lvl ) THEN
       
      BEGIN
         raise_application_error(-20001, 'The level for job_id:%d should be between %d and %d.' );
         ROLLBACK;
         
      
      END;
      END IF;
   END IF;

END;
*/
-- PROMPT Creating Foreign Key Constraint FK_RoySchedTitles on TABLE dbo.titles...
ALTER TABLE dbo.roysched
ADD CONSTRAINT FK_RoySchedTitles FOREIGN KEY
(
  title_id
)
REFERENCES titles
(
  title_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_DiscountsStore on TABLE dbo.stores...
ALTER TABLE dbo.discounts
ADD CONSTRAINT FK_DiscountsStore FOREIGN KEY
(
  stor_id
)
REFERENCES stores
(
  stor_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_EmployeeJobs on TABLE dbo.jobs...
ALTER TABLE dbo.employee
ADD CONSTRAINT FK_EmployeeJobs FOREIGN KEY
(
  job_id
)
REFERENCES jobs
(
  job_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_EmployeePublishers on TABLE dbo.publishers...
ALTER TABLE dbo.employee
ADD CONSTRAINT FK_EmployeePublishers FOREIGN KEY
(
  pub_id
)
REFERENCES publishers
(
  pub_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_Pub_infoPublishers on TABLE dbo.publishers...
ALTER TABLE dbo.pub_info
ADD CONSTRAINT FK_Pub_infoPublishers FOREIGN KEY
(
  pub_id
)
REFERENCES publishers
(
  pub_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_TitlesPublishers on TABLE dbo.publishers...
ALTER TABLE dbo.titles
ADD CONSTRAINT FK_TitlesPublishers FOREIGN KEY
(
  pub_id
)
REFERENCES publishers
(
  pub_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_salesStores on TABLE dbo.stores...
ALTER TABLE dbo.sales
ADD CONSTRAINT FK__sales__stor_id FOREIGN KEY
(
  stor_id
)
REFERENCES stores
(
  stor_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_TitleauthorTitles on TABLE dbo.titles...
ALTER TABLE dbo.titleauthor
ADD CONSTRAINT FK_TitleauthorTitles FOREIGN KEY
(
  title_id
)
REFERENCES titles
(
  title_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_salesTitles on TABLE dbo.titles...
ALTER TABLE dbo.sales
ADD CONSTRAINT FK__sales__title_id FOREIGN KEY
(
  title_id
)
REFERENCES titles
(
  title_id
)
ENABLE
;

-- PROMPT Creating Foreign Key Constraint FK_TitleauthorAuthors on TABLE dbo.authors...
ALTER TABLE dbo.titleauthor
ADD CONSTRAINT FK_TitleauthorAuthors FOREIGN KEY
(
  au_id
)
REFERENCES authors
(
  au_id
)
ENABLE
;

COMMIT;

