dialects = ["TEXT"]
rules = ["(?i)SELECT\\s+?([]\\[\\w]+[,\\s]+)+FROM\\s+?([]\\[\\w]+\\s+?)+JOIN"]
passOnRegexMatch = false
description = "If a query involving a join, it is safer to specify the table origin of a column."