
SET foreign_key_checks = 0;

-- Dropping tables ...

-- Dropping dbo.titleview ...
  DROP  VIEW IF EXISTS dbo.titleview;
-- Dropping dbo.reptq3 ...
  DROP PROCEDURE IF EXISTS  dbo.reptq3;
-- Dropping dbo.reptq2 ...
  DROP PROCEDURE IF EXISTS  dbo.reptq2;
-- Dropping dbo.reptq1 ...
  DROP PROCEDURE IF EXISTS  dbo.reptq1;
-- Dropping dbo.byroyalty ...
  DROP PROCEDURE IF EXISTS  dbo.byroyalty;
-- Dropping dbo.titleauthor ...
  DROP TABLE  IF EXISTS  dbo.titleauthor;
-- Dropping dbo.sales ...
  DROP TABLE  IF EXISTS  dbo.sales;
-- Dropping dbo.roysched ...
  DROP TABLE  IF EXISTS  dbo.roysched;
-- Dropping dbo.pub_info ...
  DROP TABLE  IF EXISTS  dbo.pub_info;
-- Dropping dbo.discounts ...
  DROP TABLE  IF EXISTS  dbo.discounts;
-- Dropping dbo.stores ...
 DROP TABLE  IF EXISTS  dbo.stores;
-- Dropping dbo.titles ...
DROP TABLE  IF EXISTS  dbo.titles; 
-- Dropping dbo.publishers ...
  DROP TABLE  IF EXISTS  dbo.publishers;
-- Dropping dbo.jobs ...
  DROP TABLE  IF EXISTS  dbo.jobs;
-- Dropping dbo.employee ...
  DROP TABLE  IF EXISTS  dbo.employee;
-- Dropping dbo.authors ...
  DROP TABLE  IF EXISTS  dbo.authors;
-- Dropping types ...

SET foreign_key_checks = 1;
